site:
  title: jMonkeyEngine Docs
  url: https://wiki.jmonkeyengine.org
  robots: allow
  start_page: docs::documentation.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
  - url: https://github.com/jMonkeyEngine/wiki-ui
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://github.com/jMonkeyEngine/wiki-ui/releases/latest/download/ui-bundle.zip
    # Required when using cache or fetch will not update ui.
    snapshot: true
asciidoc:
  # Some built-in AsciiDoc attributes are not applicable in the Antora
  # environment. These attributes include data-uri, allow-uri-read, docinfo,
  # linkcss, noheader, nofooter, webfonts, and outfilesuffix.
  attributes:
    # previous and next page navigation, uses nav.adoc
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
    #add an <orgname> element
    orgname: 'jMonkeyEngine'
    # Site wide setting of javaDoc url. Soft set using '@' allows override at
    # component and page level.
    link-javadoc: 'https://javadoc.jmonkeyengine.org/v3.4.1-stable@'
    # Enables the UI macros (button, menu and kbd)
    experimental: ''
    # Adds an anchor in front of the section title when the mouse cursor hovers
    # over it.
    :sectanchors: ''
  extensions:
  # Twitter Emoji
  # see: https://github.com/Mogztter/asciidoctor-emoji
  - asciidoctor-emoji
runtime:
  cache_dir: ./.cache/antora
  fetch: true
